### ISSUE TITLE
JSON schema draft-04 error in RegEx Keys

### ISSUE THREAD

**Issue by DaTebe** [dslik/snon-spec#1]
Hi,

**maybe** I found an error in your JSON schema file.

There are two RegEx fields which are not accepted by JSON schema validators like DJV and AJV. They are locaded in the `patternProperties` field.

```
"patternProperties": {
  "^*": {
    "$ref": "#/definitions/type_intl_name"
  }
}
```

The regular expression is not accepted. I changed it to `^.*`. I hope the behavior is still as intended?

**Comment by dslik** [comment]
Let me run that change against my regression tests, and see if it still matches against the edge cases/invalid cases.

**Comment by dslik** [comment]
Resolved in SNON 3 schema.
