### ISSUE TITLE
Incorrect invalidation if last digit of timestamp is zero 

### ISSUE THREAD

**Issue by SimonKienzler** [dslik/snon-spec#4]
Hi @dslik , we're using the SNON spec in a current project. Thanks for maintaining it. Recently, we stumbled over some weird behavior that might interest you.

Using the http://www.snon.org/v2/snon-schema.json, we got some weird rejects with the following JSON:

```
[
  {
    "eID": "urn:uuid:1635a44f-b770-4418-8f05-e721823e8e41",
    "v": [
      "1"
    ],
    "vT": [
      "2020-06-12T12:09:43.579Z"
    ]
  },
  {
    "eID": "urn:uuid:af049731-2ce2-3ed4-870c-e713c448c6d5",
    "v": [
      "1"
    ],
    "vT": [
      "2020-06-08T09:28:28.530Z"
    ]
  }
]
```

The first entry is fine, the second however is apparently invalid. The last zero of the milliseconds part seems to be the culprit. Switching it for any other digit results in a valid object according to the validator. The timestamp regex, which we tested separately, works fine. So it's some weird behavior with the validators, I assume. In the project we're using https://github.com/ajv-validator/ajv, but it can be replicated using https://www.jsonschemavalidator.net/.

Our workaround was to swap the regex with another, less restrictive one that works for our use case.

Just interested what you think of this. Appreciate any feedback :)

**Comment by dslik** [comment]
I'll take a look at this this weekend. I've primarily been using JSON::Validator from the json-schema gem to test this, so I'll expand the tests to use a few other validators too to get some wider coverage.

**Comment by dslik** [comment]
Still working on a full set of test cases for the schemas.

**Comment by dslik** [comment]
I'm unable to reproduce this with the latest schema for SNON 3.

Can you check to see if this update works for you?

**Comment by SimonKienzler** [comment]
Using the SNON Schema v3 to validate the following input works fine:

```json
[
    {
      "entityID": "urn:uuid:1635a44f-b770-4418-8f05-e721823e8e41",
      "value": [
        "1"
      ],
      "valueTime": [
        "2020-06-12T12:09:43.579Z"
      ]
    },
    {
      "entityID": "urn:uuid:af049731-2ce2-3ed4-870c-e713c448c6d5",
      "value": [
        "1"
      ],
      "valueTime": [
        "2020-06-08T09:28:28.530Z"
      ]
    }
  ]
```

However, using the short syntax (`eID`,`v`,`vT`) like in the original fragment I posted above, still leads to errors with both ajv (the validator we use in the project) and https://www.jsonschemavalidator.net/. In fact, even the official example 4.2 from http://www.snon.org/, the compact form of a single value message, is rejected by both validators. Is the short message format deprecated? The changelog for v3 says "Retired SNON Messages", I'm not sure what exactly is meant by that. Could you please clarify?

If the short message format is still supported in v3, a test case containing that format should be added to https://github.com/dslik/snon-spec/blob/master/tests/input.json - are you looking for contributions here?

**Comment by dslik** [comment]
Short syntax is still supported and should work. I'll add additional tests to the input.json test file and see if I can find out what is going on.

**Comment by dslik** [comment]
Schema had "vt" instead of "vT". Short syntax tests added to verify.

The changelog entry "Retired SNON messages" refers to the older SNON message encapsulation  format. (messageID, messageTime, etc)

Let me know if these fixes address your issue.

**Comment by SimonKienzler** [comment]
They do, thanks for the clarification and the fix!
