### ISSUE TITLE
Incorrect vTo definition in v2/snon-schema.json

### ISSUE THREAD

**Issue by knowack1** [dslik/snon-spec#6]
Hello,

in table 2.6 Value SNON Fields the vTo (valueTimeout) is described as "JSON Array of JSON Strings".
However in v2/snon-schema.json it is #/definitions/type_numeric_string.

I suppose there is wrong vTo definition in v2/snon-schema.json, should be rather #/definitions/type_string_array.

Best regards,
Karol

**Comment by dslik** [comment]
I have reproduced this issue with the schemas, and fixed it in the SNON v3 schema.

Let me know if you need it backported to the v2 schema.

**Comment by knowack1** [comment]
Hi,

Thank you for the fix. I do not need backport to v2.

Best regards,
Karol
